setBatchMode(true);
original = getTitle();
run("Select None");
run("Duplicate...", "title=blurred");
run("Gaussian Blur...", "sigma=10");
//run("Morphological Filters", "operation=Closing element=Disk radius=10");
setAutoThreshold("Otsu dark");
run("Convert to Mask");
run("Skeletonize (2D/3D)");
rename("skeleton");
run("Analyze Skeleton (2D/3D)", "prune=[shortest branch] prune_1 calculate");
run("Keep Largest Label");
run("Options...", "iterations=2 count=1 black do=Close");
run("Dilate");
run("Keep Largest Region");
run("Skeletonize (2D/3D)");
run("Invert");
run("Create Selection");
selectWindow(original);
close("\\Others");
run("Restore Selection");